---
# some handlers
- name: reload_systemctl
  become: true
  become_user: "{{ awxpod_container_run_as_user }}"
  environment:
    XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
  systemd:
    daemon_reload: true
    scope: "{{ systemd_scope }}"

- name: start_service
  become: true
  become_user: "{{ awxpod_container_run_as_user }}"
  environment:
    XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
  systemd:
    name: "{{ service_name }}"
    scope: "{{ systemd_scope }}"
    state: started

- name: restart_service
  become: true
  become_user: "{{ awxpod_container_run_as_user }}"
  environment:
    XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
  systemd:
    name: "{{ service_name }}"
    scope: "{{ systemd_scope }}"
    state: restarted

- name: enable_service
  become: true
  become_user: "{{ awxpod_container_run_as_user }}"
  environment:
    XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
  systemd:
    name: "{{ service_name }}"
    enabled: true
    scope: "{{ systemd_scope }}"
